export const fleetVehicles = [
  {
    name: "Tesla Model Y Juniper",
    category: "Électrique",
    image: "/tesla.png",
    slug: "tesla-model-y-juniper",
    badges: ["Nouveauté"],
    eligibility: "ÉLIGIBILITÉ UBER",
    monthlyPrice: "1250 € / mois",
    weeklyPrice: "312 € / semaine",
    summary: "Autonomie longue distance et conduite assistée avancée.",
    specs: {
      seats: "5 places",
      motorisation: "Électrique",
      trunk: "854 L",
      puissanceDIN: "378 ch",
      puissanceFiscale: "11 CV",
      cylindree: "82 kWh",
      garage: "Stationnement inclus",
    },
    technical: [
      "Emissions de CO₂ : 0 g/km",
      "Capacité batterie : 82 kWh",
      "Autonomie : jusqu’à 565 km",
      "Recharge DC : 210 kW / 25 min",
    ],
    dimensions: {
      length: "475 cm",
      width: "192 cm",
      height: "162 cm",
    },
    equipments: [
      "Pilote automatique amélioré",
      "Pompe à chaleur",
      "Sièges chauffants avant et arrière",
      "Écran central 15 pouces",
      "Caméras 360°",
      "Portes USB-C rapides",
      "Système audio Premium",
      "Hayon électrique",
      "Vitres arrière surteintées",
      "Volant chauffant",
      "Jantes 20 pouces",
    ],
    leasing: {
      title: "LOCATION LONGUE DURÉE",
      engagement: "3 mois / sans engagement",
      pack: "Pack Assurance FlexiFleet",
      vehicle: {
        monthly: "1250 € TTC / mois",
        weekly: "312 € TTC / semaine",
        baseKm: "6000 km / mois",
        duration: "48 mois",
        advantages: [
          "Loyers ajustables selon l’activité",
          "Livraison sous 72h",
          "Entretien et assistance inclus",
        ],
      },
      insurance: {
        monthly: "265 € / mois",
        weekly: "66.25 € / semaine",
        coverage: [
          "Assurance tous risques",
          "Protection valeur à neuf",
          "Assistance 0 km",
          "Responsabilité Civile Professionnelle",
        ],
      },
    },
  },
  {
    name: "KIA EV6 GT-line",
    category: "Électrique",
    image: "/placeholder.jpg",
    slug: "kia-ev6-gt-line",
    badges: ["Nouveauté"],
    eligibility: "ÉLIGIBILITÉ UBER",
    monthlyPrice: "1233 € / mois",
    weeklyPrice: "308 € / semaine",
    summary: "L’alliance de la performance électrique et du confort GT-line.",
    specs: {
      seats: "5 places",
      motorisation: "Électrique",
      trunk: "480 L",
      puissanceDIN: "229 ch",
      puissanceFiscale: "4 CV",
      cylindree: "77 kWh",
      garage: "Stationnement sécurisé",
    },
    technical: [
      "Emissions de CO₂ : 0 g/km",
      "Capacité de batterie : 77 kWh",
      "Autonomie : jusqu’à 530 km",
      "Recharge DC : 150 kW / 27 min",
    ],
    dimensions: {
      length: "470 cm",
      width: "189 cm",
      height: "155 cm",
    },
    equipments: [
      "Aide au maintien dans la file (LKA)",
      "Allumage automatique des projecteurs",
      "Assistance embouteillages (LFA)",
      "Caméra de recul avec guidage dynamique",
      "Climatisation automatique bi-zone",
      "Instrumentation digitale 12,3 pouces",
      "Finition GT-line",
      "ISOFIX deuxième rangée",
      "Radars avant et arrière",
      "Rétroviseur intérieur électrochrome",
      "Vitres arrière surteintées",
      "Volant chauffant",
      "Jantes alliage 19 pouces",
    ],
    leasing: {
      title: "LOCATION LONGUE DURÉE",
      engagement: "3 mois / sans engagement",
      pack: "Pack Assurance FlexiFleet",
      vehicle: {
        monthly: "1233 € TTC / mois",
        weekly: "308 € TTC / semaine",
        baseKm: "6000 km / mois",
        duration: "48 mois",
        advantages: [
          "Loyers adaptés à votre activité",
          "Trésorerie maîtrisée",
          "Maintenance incluse",
        ],
      },
      insurance: {
        monthly: "275 € / mois",
        weekly: "68.75 € / semaine",
        coverage: [
          "Garantie immobilisation",
          "RC Circulation",
          "Dommages tous accidents",
          "Perte financière",
          "Assistance 0 km",
          "RC Professionnelle",
        ],
      },
    },
  },
  {
    name: "BYD Seal Performance",
    category: "Électrique",
    image: "/placeholder.jpg",
    slug: "byd-seal-performance",
    badges: ["Exclusivité"],
    eligibility: "ÉLIGIBILITÉ UBER",
    monthlyPrice: "1100 € / mois",
    weeklyPrice: "275 € / semaine",
    summary: "Berline électrique performante à double moteur.",
    specs: {
      seats: "5 places",
      motorisation: "Électrique",
      trunk: "400 L",
      puissanceDIN: "390 ch",
      puissanceFiscale: "10 CV",
      cylindree: "82 kWh",
      garage: "Parking premium",
    },
    technical: [
      "Emissions de CO₂ : 0 g/km",
      "Capacité batterie : 82 kWh",
      "Autonomie : jusqu’à 520 km",
      "Recharge DC : 150 kW / 26 min",
    ],
    dimensions: {
      length: "480 cm",
      width: "188 cm",
      height: "146 cm",
    },
    equipments: [
      "Toit panoramique",
      "Sellerie vegan premium",
      "Écran central 15,6 pouces pivotant",
      "Surround view 360°",
      "Chargeur rapide sans fil",
      "Système audio Dynaudio",
      "Régulateur adaptatif",
      "Freinage d’urgence autonome",
      "Detection angle mort",
      "Vitres acoustiques",
      "Jantes 19 pouces",
    ],
    leasing: {
      title: "LOCATION LONGUE DURÉE",
      engagement: "3 mois / sans engagement",
      pack: "Pack Assurance FlexiFleet",
      vehicle: {
        monthly: "1100 € TTC / mois",
        weekly: "275 € TTC / semaine",
        baseKm: "5500 km / mois",
        duration: "48 mois",
        advantages: [
          "Livraison rapide",
          "Batterie garantie 8 ans",
          "Support conducteur 24/7",
        ],
      },
      insurance: {
        monthly: "250 € / mois",
        weekly: "62.5 € / semaine",
        coverage: [
          "Tous risques",
          "Assistance 0 km",
          "Protection juridique",
          "RC Professionnelle",
        ],
      },
    },
  },
  {
    name: "Volkswagen ID.4 Pro",
    category: "Électrique",
    image: "/placeholder.jpg",
    slug: "volkswagen-id4-pro",
    badges: ["Nouveauté"],
    eligibility: "ÉLIGIBILITÉ UBER",
    monthlyPrice: "1033 € / mois",
    weeklyPrice: "258 € / semaine",
    summary: "SUV électrique confortable et modulable.",
    specs: {
      seats: "5 places",
      motorisation: "Électrique",
      trunk: "543 L",
      puissanceDIN: "204 ch",
      puissanceFiscale: "5 CV",
      cylindree: "77 kWh",
      garage: "Stationnement inclus",
    },
    technical: [
      "Emissions de CO₂ : 0 g/km",
      "Capacité batterie : 77 kWh",
      "Autonomie : jusqu’à 520 km",
      "Recharge DC : 135 kW / 30 min",
    ],
    dimensions: {
      length: "458 cm",
      width: "185 cm",
      height: "164 cm",
    },
    equipments: [
      "Cockpit digital 10 pouces",
      "Head-up display AR",
      "Climatisation tri-zone",
      "Assistants Travel Assist",
      "Caméra de recul",
      "Radar avant et arrière",
      "Keyless Access",
      "Volant chauffant",
      "Chargeur USB-C double",
      "Vitres arrière surteintées",
      "Jantes 19 pouces",
    ],
    leasing: {
      title: "LOCATION LONGUE DURÉE",
      engagement: "3 mois / sans engagement",
      pack: "Pack Assurance FlexiFleet",
      vehicle: {
        monthly: "1033 € TTC / mois",
        weekly: "258 € TTC / semaine",
        baseKm: "5000 km / mois",
        duration: "48 mois",
        advantages: [
          "Confort optimisé pour trajets longue durée",
          "Gestion de flotte simplifiée",
          "Maintenance Volkswagen Pro",
        ],
      },
      insurance: {
        monthly: "240 € / mois",
        weekly: "60 € / semaine",
        coverage: [
          "Tous risques",
          "Assistance 0 km",
          "Véhicule de remplacement",
          "RC Professionnelle",
        ],
      },
    },
  },
  {
    name: "Mercedes EQE 350+",
    category: "Berline Électrique",
    image: "/mercedes-sclass.png",
    slug: "mercedes-eqe-350-plus",
    badges: ["Stock Limité"],
    eligibility: "ÉLIGIBILITÉ UBER",
    monthlyPrice: "1350 € / mois",
    weeklyPrice: "338 € / semaine",
    summary: "Berline executive 100% électrique, confort S-Class.",
    specs: {
      seats: "5 places",
      motorisation: "Électrique",
      trunk: "430 L",
      puissanceDIN: "292 ch",
      puissanceFiscale: "13 CV",
      cylindree: "90 kWh",
      garage: "Parking sécurisé",
    },
    technical: [
      "Emissions de CO₂ : 0 g/km",
      "Capacité batterie : 90 kWh",
      "Autonomie : jusqu’à 610 km",
      "Recharge DC : 170 kW / 32 min",
    ],
    dimensions: {
      length: "495 cm",
      width: "196 cm",
      height: "151 cm",
    },
    equipments: [
      "MBUX Hyperscreen",
      "Suspension AIRMATIC",
      "Sièges ventilés et massants",
      "Pack Chauffeur",
      "Burmeister 3D Sound",
      "Projecteurs DIGITAL LIGHT",
      "Commande gestuelle",
      "Climatisation 4 zones",
      "Vitres acoustiques",
      "Volant chauffant",
      "Jantes 20 pouces",
    ],
    leasing: {
      title: "LOCATION LONGUE DURÉE",
      engagement: "3 mois / sans engagement",
      pack: "Pack Assurance FlexiFleet",
      vehicle: {
        monthly: "1350 € TTC / mois",
        weekly: "338 € TTC / semaine",
        baseKm: "6500 km / mois",
        duration: "48 mois",
        advantages: [
          "Image prestige pour clientèle exécutive",
          "Remplacement véhicule sous 24h",
          "Maintenance Mercedes Pro",
        ],
      },
      insurance: {
        monthly: "295 € / mois",
        weekly: "73.75 € / semaine",
        coverage: [
          "Tous risques",
          "Assistance 0 km",
          "Protection juridique",
          "RC Professionnelle",
        ],
      },
    },
  },
  {
    name: "BMW i7 Black Edition",
    category: "Berline Électrique",
    image: "/bmw-i7-black-luxury-sedan-electric.jpg",
    slug: "bmw-i7-black-edition",
    badges: ["Exclusivité"],
    eligibility: "ÉLIGIBILITÉ UBER",
    monthlyPrice: "1420 € / mois",
    weeklyPrice: "355 € / semaine",
    summary: "Flagship électrique avec technologie Executive Lounge.",
    specs: {
      seats: "4+1 places",
      motorisation: "Électrique",
      trunk: "500 L",
      puissanceDIN: "544 ch",
      puissanceFiscale: "17 CV",
      cylindree: "101 kWh",
      garage: "Service voiturier",
    },
    technical: [
      "Emissions de CO₂ : 0 g/km",
      "Capacité batterie : 101 kWh",
      "Autonomie : jusqu’à 625 km",
      "Recharge DC : 195 kW / 28 min",
    ],
    dimensions: {
      length: "539 cm",
      width: "195 cm",
      height: "154 cm",
    },
    equipments: [
      "Cinema Screen 31 pouces",
      "Sièges arrière Executive Lounge",
      "BMW Interaction Bar",
      "Système audio Bowers & Wilkins",
      "Pack Chauffeur VIP",
      "Head-up display",
      "Ambiance lumineuse personnalisable",
      "Portes soft-close",
      "Climatisation 4 zones",
      "Tablettes arrière",
      "Jantes 21 pouces",
    ],
    leasing: {
      title: "LOCATION LONGUE DURÉE",
      engagement: "3 mois / sans engagement",
      pack: "Pack Assurance FlexiFleet",
      vehicle: {
        monthly: "1420 € TTC / mois",
        weekly: "355 € TTC / semaine",
        baseKm: "7000 km / mois",
        duration: "48 mois",
        advantages: [
          "Prestige absolu pour clientèle VIP",
          "Service chauffeur remplaçant",
          "Garanties BMW Excellence",
        ],
      },
      insurance: {
        monthly: "320 € / mois",
        weekly: "80 € / semaine",
        coverage: [
          "Tous risques",
          "Assistance 0 km",
          "Protection valeur à neuf",
          "RC Professionnelle",
        ],
      },
    },
  },
] as const

export type FleetVehicle = (typeof fleetVehicles)[number]
